### ISSUE TITLE
Support of profiles

### ISSUE THREAD

**Issue by ChristophSteinberg** [marklechtermann/shiprandomizer#3]
Would it be possible to add 6 profile buttons,
Profiles 1-5 mean tier 5-10 and 1 for random selection.
Levels 1-4 are rarely driven.
There are a lot of ships in the list, some that don't even exist anymore, or some that few own.
If you have chosen your list, then save it on a profile button.
The next question is, are the profiles e.g. saved with cookies when you come back, that you can choose your profile?
p.s. just write to me in Discord, I'll get back to you as soon as possible ;)

Deutsch
Wäre es möglich, 6 Profil Buttons einzufügen,
Profile 1-5 bedeuten, Tier Stufe 5-10 und 1 für Random Auswahl.
Die Stufen 1-4 werden selten gefahren.
Es sind eine Menge Schiffe in der Liste, einige, die es auch gar nicht mehr gibt, oder auch die wenigsten besitzen.
Wenn man seine Liste gewählt hat diese dann hinterlegen auf einen Profil Button.
Dazu die nächste Frage, werden die Profile z. B. mit cookies gespeichert, wenn man wieder kommt, dass man sein Profil wählen kann?
p.s. mich einfach in Discord anschreiben, ich melde mich schleunigst ;)

with the fondest regards
Graf_d

**Comment by marklechtermann** [comment]
Hi Graf_d,

first the data is stored in the browser as LocalStorage. So the settings are preserved when the website is reloaded.

It would be simpler if we basically supported profiles.
This means that after selecting a list of ships, you can simply save them as a profile.
I will have a look at this next week.
